// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGb2wBhIRemVwzbslY4-_n9d3axwJyeBM',
    appId: '1:1092061494620:android:66ba38be02dfcd57ca1599',
    messagingSenderId: '1092061494620',
    projectId: 'parkeasy2-4f0ef',
    databaseURL: 'https://parkeasy2-4f0ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkeasy2-4f0ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPjEVjc79i9vAR3XwgUq5_UINISVZmV48',
    appId: '1:1092061494620:ios:b161a1b38bca6c81ca1599',
    messagingSenderId: '1092061494620',
    projectId: 'parkeasy2-4f0ef',
    databaseURL: 'https://parkeasy2-4f0ef-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parkeasy2-4f0ef.firebasestorage.app',
    iosClientId: '1092061494620-2ka2fiiatuj69nravpd54qlmqjpjobvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkeasy2',
  );
}
